#ifndef ASSIGNMENT5_DEFINES_H
#define ASSIGNMENT5_DEFINES_H

#define PLAYER_GOAL_LEFT_EDGE_X -0.8
#define PLAYER_GOAL_RIGHT_EDGE_X 0.8
#define PLAYER_GOAL_EDGE_Z 4.0

#define AI_GOAL_LEFT_EDGE_X -0.8
#define AI_GOAL_RIGHT_EDGE_X 0.8
#define AI_GOAL_EDGE_Z -4.0

#define TABLE_LEFT_EDGE -2.0
#define TABLE_RIGHT_EDGE 2.0
#define TABLE_BACK_EDGE -4.0
#define TABLE_FRONT_EDGE 4.0

#define PUCK_RADIUS 0.2
#define MALLET_RADIUS 0.3

#endif //~ASSIGNMENT5_DEFINES_H